local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 8.0
   publish_frequency: 6.0
   width: 5.0
   height: 5.0
   resolution: 0.05
   static_map: false
   rolling_window: true
   width: 4
   height: 4
